
version: '3'

tasks:
  download:
    cmds:
      - bun scripts/download-openapi.mjs
      
  generate:
    cmds:
      - bun scripts/generate-api-docs.mjs
      
  dev:
    cmds:
      - bun i && bun run dev
