
version: '3'

tasks:
  download:
    cmds:
      - bun scripts/download-openapi.mjs

  generate:
    cmds:
      - bun scripts/generate-api-docs.mjs

  update-openapi:
    cmds:
      - bun scripts/update-openapi.mjs

  update:
    cmds:
      - task: download
      - task: update-openapi
      - task: generate

  dev:
    cmds:
      - bun i && bun run dev
